config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'


    devise_for :users,
  			  path: '',
  			  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  			  controllers: {omniauth_callbacks: 'omniauth_callbacks'}	

  	resources :users, only: [:show]
    resources :books, except: [:edit] do
      member do
          get 'listing'
          get 'pricing'
          get 'description'
          get 'photo_upload'
          get 'amenities'
          get 'location'
        end

        resources :photos, only: [:create, :destroy] 
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :photos

  paginates_per 5

  validates :subject, presence: true
  validates :book_type, presence: true
  validates :author_name, presence: true
  validates :pages, presence: true

  def cover_photo()
  	if self.photos.length > 0
  		self.photos[0].image.url()
  	else
  		"blank.jpg"
  	end
  end

 
  
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :book

  # has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

 	mount_uploader :image, FileUploader



  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable


         validates :fullname, presence: true, length: {maximum: 50}

         has_many :books

    def self.from_omniauth(auth)
     	user = User.where(email: auth.info.email).first

     	if user
     		return user
     	else
     		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		    user.email = auth.info.email
		    user.password = Devise.friendly_token[0, 20]
		    user.fullname = auth.info.name  
		    user.image = auth.info.image 
		    user.uid = auth.uid
		    user.provider = auth.provider
		    # If you are using confirmable and the provider(s) you use validate emails, 
		    # uncomment the line below to skip the confirmation emails.
		    user.skip_confirmation!
		  end		
     	end
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	 	devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
	 	devise_parameter_sanitizer.permit(:account_update, keys: [:fullname])
	 end 
end

app/controllers/book_controller.rb
class BookController < ApplicationController

  before_action :set_book, except: [:index, :new, :create] 
  before_action :authenticate_user!, except: [:show]


  def index
    @books = current_user.books
  end

  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to listing_room_path(@room), notice: "Saved.....!"
    else
      render :new, notice: "Something went wrong......."
    end
  end

  def show
    
  end

  def listing
    
  end

  def pricing
    
  end

  def description
   
  end

  def photo_upload
  end

  def amenities
  end

  def location
  end

  def update
    if @book.update(book_params)
      flash[:notice] = "Saved...."
    else
        flash[:notice] = "Something went wrong....."
      end

      redirect_back(fallback_location: request.referer)
  end

  private

  def set_book
     @book = Book.find(params[:id])
  end

  def book_params
    params.require(:room).permit(:subject, :book_type, :author_name, :pages, :listing_name, :summery, :address, :borrow, :is_paper_back, :is_pdf, :price, :active)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, except: [:index, :new, :create,:destroy] 
  before_action :authenticate_user!, except: [:show ]
  before_action :is_admin, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]


  def index
    @books = current_user.books
  end

  def new
    @books = current_user.books.order('created_at DESC').page(params[:page])
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to listing_book_path(@book), notice: "Saved.....!"
    else
      flash[:alert] = "Something Went Wrong...." 
      render :new
    end
  end

  def show
    
  end

  def listing
    
  end

  def pricing
    
  end

  def description
   
  end

  def photo_upload
    @photos = @book.photos

  end

  def amenities
  end

  def location
  end

  def update
    if @book.update(book_params)
      flash[:notice] = "Saved...."
    else
        flash[:alert] = "Something went wrong....."
      end

      redirect_back(fallback_location: request.referer)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.photos.delete_all

    if @book.destroy
        redirect_to books_path, notice: "Book Was successfully destroyed."
      else
        redirect_to books_path, error: "Something went wrong......"
      end
  end


   








  

 

  private

  def set_book
     @book = Book.find(params[:id])
  end

  def is_admin
    redirect_to root_path, alert: "Yon don't have permission...." unless current_user.id == @book.user_id
  end

 

  def book_params
    params.require(:book).permit(:subject, :book_type, :author_name, :pages, :listing_name, :summary, :address, :borrow, :is_paper_back, :is_pdf, :price, :active)
  end

end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def create
		@book = Book.find(params[:book_id])

		if params[:images]
			params[:images].each do |img|
				@book.photos.create(image: img)
			end

			@photos = @book.photos
			redirect_back(fallback_location: request.referer, notice: "Saved....")
		end 
	end

	def destroy
    @photo = Photo.find(params[:id])
    book_id = params[:book_id]

    if @photo.destroy
      redirect_to photo_upload_book_path(book_id), notice: "Photo successfully destroyed."
    else
      redirect_to photo_upload_book_path(book_id), error: "Something went wrong......"
    end
  end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

	def index
		@user = User.order(:last_name).page(params[:page])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def avatar_url(user)
		
		if user.image
			"http://graph.facebook.com/#{user.uid}/picture?type=large"
		else
			gravatar_id = Digest::MD5::hexdigest(user.email).downcase
			"https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
		end
		
	end
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book_menu.html.erb
<ul class="sidebar-list">
	<li class="sidebar-item">
		<%= link_to "Listing", listing_book_path, class: "sidebar-link active" %>
	</li>
	
	<li class="sidebar-item">
		<%= link_to "Pricing", pricing_book_path, class: "sidebar-link active" %>
	</li>
	<li class="sidebar-item">
		<%= link_to "Description", description_book_path, class: "sidebar-link active" %>
	</li>
	<li class="sidebar-item">
		<%= link_to "Photos", photo_upload_book_path, class: "sidebar-link active" %>
	</li>
	<li class="sidebar-item">
		<%= link_to "Amenities", amenities_book_path, class: "sidebar-link active" %>
	</li>
	<li class="sidebar-item">
		<%= link_to "Location", location_book_path, class: "sidebar-link active" %>
	</li>
</ul>

app/views/books/amenities.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'book_menu'%>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				Amenities
			</div>

			<div class="panel-body">
				<div class="container">
					<%= form_for @book do |b|%>
						<div class="row form-group">
							<div class="col-md-4">
								<%= b.check_box :borrow %> Borrow
							</div>
							<div class="col-md-4">
								<%= b.check_box :is_paper_back %> Paper_Back
							</div>
							<div class="col-md-4">
								<%= b.check_box :is_pdf %> PDF
							</div>
							
						</div>

						<div class="text-center">
							<%= b.submit "Save", class: "btn btn-form" %>
						</div>
					<% end -%>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/books/create.html.erb
<h1>Book#create</h1>
<p>Find me in app/views/book/create.html.erb</p>

app/views/books/description.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'book_menu'%>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				Description
			</div>

			<div class="panel-body">
				<div class="container">
					<%= form_for @book do |b|%>

						<div class="row">
							<div class="form-group">
								<label>Book Name</label>
								<%= b.text_field :listing_name, placeholder: "What is your Book Nmae?", class: "form-control", required: true %>
							</div>
						</div>
						<div class="row">
							<div class="form-group">
								<label>Summary</label>
								<%= b.text_area :summary, rows: 5, placeholder: "Summary of your book.", class: "form-control", required: true %>
							</div>

						</div>

						<div class="text-center">
							<%= b.submit "Save", class: "btn btn-form" %>
						</div>


								
					<% end -%>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			
		<li class="sidebar-item"><%= link_to "Ener New Book", new_book_path, class: "btn btn-form"%></li>
		</ul>
	</div>
	<div class="col-md-9">

		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">
					Book List
				</div>
			</div>
			<div class="panel-body">
				
				
				<table class="table">
				  <thead>
				    <tr>
				      <th scope="col">SL</th>
				      <th scope="col">Book Cover Image</th>
				      <th scope="col">Title</th>
				      <th scope="col">Description</th>
				      <th scope="col">Auther</th>
				      <th scope="col">Pages</th>
				      <th scope="col">Action</th>
				    </tr>
				  </thead>
				  	<tbody>
				  		<% li = 0 %>
				  		<% @books.each do |book|%>
				  		<% li = li + 1%>
							<tr>
								<td><%= li %></td>
								<td><%= image_tag book.cover_photo() %></td>
								<td><%= book.listing_name %></td>
								<td><%= book.summary%></td>
								<td><%= book.author_name%></td>
								<td><%= book.pages%></td>
								<td><%= link_to 'Show', book_path(book) %> |  
									<%= link_to "Edit", listing_book_path(book)%> |  
									<%= link_to "Delete", book_path(book), method: :delete, data: {confirm: "Are you sure?"} %> </td>

							</tr>
				  		<% end -%>
				  </tbody>
				</table>
				
			<%= paginate @books %>
			</div>
		</div>
	</div>
</div>

app/views/books/listing.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render'book_menu'%>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				listing
			</div>

			<div class="panel-body">
				<div class="container">
					<%= form_for @book do |b|%>

				<div class="row">
					<div class="col-md-4 select">
						<div class="form-group">
							<label>Subjects</label>
							<%= b.select :subject, [["Arts","Arts"], ["Animals","Animals"], ["Fiction","Fiction"], ["Science & Mathematics", "Science & Mathematics"]], 
							     id: "subject", prompt: " Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Book Type</label>
							<%= b.select :book_type, [["Architecture","Architecture"], [" Art Instruction"," Art Instruction"], [" Art History"," Art History"]],
							     id: "book_type", prompt: " Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Author Name</label>
							<%= b.select :author_name, [["Mahi Chowdhury","Mahi Chowdhury"], ["Oshim","Oshim"], ["Bishal","Bishal"], ["Rayhan ", "Rayhan "]], 
							     id: "author_name", prompt: " Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Pages</label>
							<%= b.select :pages, [["100", 100], ["150", 150], ["200+", 200]], 
							     id: "pages", prompt: " Select...", class: "form-control" %>
						</div>
					</div>
				</div><br><br>
					<div class="row">
						<div class="col-md-4">
							<div><%=  b.submit "Save", class: "btn btn-normal" %></div>
						</div>
						<div class="col-md-4">
							<%= link_to 'Book List', books_path, class: "btn btn-form" %>
						</div>

					</div>

				
				

			<% end -%>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/books/location.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'book_menu'%>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				Location
			</div>

			<div class="panel-body">
				<div class="container">
					<%= form_for @book do |b|%>
					 <div class="row">
					 	<div class="form-group">
					 		<label>Address</label>
					 		<%= b.text_field :address, placeholder: "What is your address?", class: "form-control", required: true %>
					 	</div>
					 </div>

					 <div class="text-center">
					 	<%= b.submit "Save", class: "btn btn-form" %>
					 </div>

					<% end -%>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/books/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Add Your Book Here
	</div>
	<div class="panel-body">
		<div class="container">
			<%= form_for @book do |b|%>

				<div class="row">
					<div class="col-md-4 select">
						<div class="form-group">
							<label>Subjects</label>
							<%= b.select :subject, [["Arts","Arts"], ["Animals","Animals"], ["Fiction","Fiction"], ["Science & Mathematics", "Science & Mathematics"]], 
							     id: "subject", prompt: " Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Book Type</label>
							<%= b.select :book_type, [["Architecture","Architecture"], [" Art Instruction"," Art Instruction"], [" Art History"," Art History"]],
							     id: "book_type", prompt: " Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Author Name</label>
							<%= b.select :author_name, [["Mahi Chowdhury","Mahi Chowdhury"], ["Oshim","Oshim"], ["Bishal","Bishal"], ["Rayhan ", "Rayhan "]], 
							     id: "author_name", prompt: " Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Pages</label>
							<%= b.select :pages, [["100", 100], ["150", 150], ["200+", 200]], 
							     id: "pages", prompt: " Select...", class: "form-control" %>
						</div>
					</div>
				</div><br><br>

				<div><%=  b.submit "Entry Your Book", class: "btn btn-normal" %></div>

			<% end -%>
		</div>
	</div>
	
</div>

app/views/books/photo_upload.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'book_menu'%>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				Photos
			</div>

			<div class="panel-body">
				<div class="container">
					<div class="row">
						<div class="col-md-offset-3 col-md-6">
							<!-- Photos Upload Goes Here -->

							<%= form_for @book, url: book_photos_path(@book), method: 'post', html: {multipart: true} do |f| %>
								<div class="row">
									<div class="form-group">
										<span class="btn btn-default btn-file text-babu">
											<i class="fas fa-upload"></i> Select Photos
											<%= file_field_tag "images[]", type: :file, multiple: true %>
										</span>
									</div>
								</div>

								<div class="text-center">
									<%= f.submit "Add Photos", class: "btn btn-form" %>
								</div>
							<% end -%>
						</div>			
					</div>

					<div class="" id="photos"><%= render 'photos/photos_list' %></div>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/books/pricing.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render'book_menu'%>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">

			<div class="panel-heading">
				Pricing
			</div>

			<div class="panel-body">
				<div class="container">
					<%= form_for @book do |b|%>
					 <div class="row">
					 	<div class="form-group">
					 		<label>Price</label>
					 		<%= b.text_field :price, placeholder: "$ 250", class: "form-control", required: true %>
					 	</div>
					 </div>

					 <div class="text-center">
					 	<%= b.submit "Save", class: "btn btn-form" %>
					 </div>

					<% end -%>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/books/show.html.erb
<!-- Image -->

<div class="row">
	<div class="col-md-12">
		<%= image_tag @book.cover_photo(), width: "100%" %>
	</div>
</div>

<br>



<div class="row">
	<!-- Left Pannel -->
	<div class="col-md-8">
		<!-- Info Listing Name -->
		<div class="row">
			<div class="col-md-8">
				<h1><%= @book.listing_name %></h1>
				<%= @book.address %>
			</div>
			<div class="col-md-4 text-center">
				<%= image_tag avatar_url(@book.user), class: "img-circle avatar_large" %> <br><br>
				<%= @book.user.fullname%>
			</div>
		</div>
		<hr>

		<!-- Info Book -->
		<div class="row text-babu">
			<div class="row text-center row-space-1">
				<div class="col-md-3">
					<i class="fa fa-book" aria-hidden="true"></i>
				</div>
				<div class="col-md-3">
					<i class="fa fa-file" aria-hidden="true"></i>
				</div>
				<div class="col-md-3">
					<i class="fas fa-user"></i>
				</div>
				<div class="col-md-3">
					<i class="fa fa-file-text-o" aria-hidden="true"></i>
				</div>
			</div>

			<div class="row text-center">
				<div class="col-md-3"><%= @book.subject %></div>
				<div class="col-md-3"><%= @book.book_type %></div>
				<div class="col-md-3"><%= @book.author_name %></div>
				<div class="col-md-3"><%= @book.pages %></div>
			</div>
		</div>
		<hr>

		<!-- Info About -->
		<div class="row">
			<div class="col-md-12">
				<h4>About this Book</h4>
				<%= @book.summary%>
			</div>
		</div>
		<hr>

		<!-- Info Amenities -->
		<div class="row">
			<div class="col-md-3">
				<h3>Amenities</h3>
			</div>
			<div class="col-md-9">
				
						<ul class="amenities">
							<li class="<%= 'text-line-through' if !@book.borrow %>">Borrow</li>
							<li class="<%= 'text-line-through' if !@book.is_pdf %>">Pdf</li>
							<li class="<%= 'text-line-through' if !@book.is_paper_back%>">Paper_back</li>
						</ul>
					
			</div>
		</div>
		<hr>

		

		
	</div>

	
	<!-- Right Pannel -->
	<div class="col-md-4"></div>
</div>

app/views/books/update.html.erb
<h1>Book#update</h1>
<p>Find me in app/views/book/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookLib</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

    <%= render 'shared/navbar'%>
    <%= render 'shared/message'%>

    

    <div class="container">
     <%= yield %>  
    </div>
    
  </body>

  <script src="https://kit.fontawesome.com/dacfff56d6.js" crossorigin="anonymous"></script>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
	<br><br>

	<div class="row">
		<% @photos.each do |ph|%>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading preview">
						<%= image_tag ph.image.url()%>
					</div>

					<div class="panel-body">
						<span class="pull-right">
							<%= link_to book_photo_path(ph.book_id, ph), remote: true, method: :delete, data: {confirm: "Are you sure?"}  do  %>
							<i class="fas fa-trash-alt"></i>

							<% end -%>
						</span>
					</div>


				</div>
			</div>
		<% end -%>
	</div>

<% end -%>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	
	<script type="text/javascript">
		<% flash.each do |key, value| %>
			<% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
			toastr['<%= type %>']('<%= value %>')
		<% end -%>
	</script>
<% end -%>

app/views/shared/_navbar.html.erb
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="row">
          <div class="col-md-9"> <!-- menu area start -->
            <div class="menu-area">
              <ul class="nav navbar-nav">
                <li class="book-library"><a href="">Book Library</a></li>
                <li class="dropdown">
                        <a href="#" class="dropdown-toggle_1" data-toggle="dropdown"
                              role="button" aria-haspopup="true" aria-expanded="false">
                              DISCOVER <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Action & Adventure </a></li>
                          <li><a href="#">Bios & History</a></li>
                          <li><a href="#">Children's</a></li>
                          <li><a href="#">Fantasy</a></li>
                          <li><a href="#">Historical Fiction</a></li>
                          <li><a href="#">Horror</a></li>
                          <li><a href="#">Literary Fiction</a></li>
                          <li><a href="#">Mystery & Thriller</a></li>
                          <li><a href="#">Non Fiction</a></li>
                          <li><a href="#">Romance</a></li>
                          <li><a href="#">Science Fiction</a></li>
                          <li><a href="#">Young Adult</a></li>
                          <li role="separator" class="divider"></li>
                          <li><a href="#">Young Adult</a></li>
                        </ul>
                      </li>
              </ul>
            </div><!-- menu area end -->
            
          </div>
          <div class="col-md-3">
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <% if (!user_signed_in?) %>
                  
                  <li><%= link_to "Login", new_user_session_path %></li>
                  <li><%= link_to "SignUp", new_user_registration_path %></li>
                  
                <% else %>
                     <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                              role="button" aria-haspopup="true" aria-expanded="false">
                              <%= image_tag avatar_url(current_user),  class: "img-circle avatar_small"%>&nbsp;
                              <%= current_user.fullname%> <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                          <li><a href="#"></a></li>
                        
                          
                          <li><%= link_to "Book List", books_path %></li>
                          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                          
                        </ul>
                      </li>

                <% end -%>
               
              </ul>
            
            </div><!--/.nav-collapse -->
            
          </div>
        </div>


      </div>
    </nav>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-3">
		<div class="center">
			<%= image_tag avatar_url(@user), class: "avatar_full" %>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">Varification</div>
			<div class="panel-body">
				Email Address <br>
				Phone Number
			</div>
		</div>
	</div>
	<div class="col-md-9">
		<h2><%= @user.fullname %></h2>

		<div class="description row-space-3">
			<%= @user.description %>
		</div>
	</div>
</div>